### ISSUE TITLE
out of bounds issue when compute_gbest is called

### ISSUE THREAD

**Issue by cembry26** [ljvmiranda921/pyswarms#361]
* PySwarms version:1.1.0
* Python version:3.7.4
* Operating System:Windows 10

# Description

Howdy!

I'm trying to tune the hyperparameters of xgboost trees utilizing this library, and I'm hitting an issue with the compute_gbest of the ring class going out of bounds of the swarm.pbest_cost.

I'm not sure if my passing of results from my cost function is the issue or if it is on your end.

# What I Did

NOTE - I am omitting ample unrealted code to this. Let me know if you want any additional tidbits!

### Cost function

```
import xgboost as xgb
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np


def xgboost_hp_search(params, X, y, eval_metric):
    results = []
    num_rows = np.shape(params)[0]

    params_to_use = params.copy()

    for i in range(num_rows):

        params = {
            # 'tree_method': 'gpu_hist',
            'eta': params_to_use[i, 0],
            'gamma': params_to_use[i, 1],
            'max_depth': int(params_to_use[i, 2]),
            'min_child_weight': params_to_use[i, 3],
            'max_delta_step': params_to_use[i, 4],
            'subsample': params_to_use[i, 5],
            'colspace_bytree': params_to_use[i, 6]
        }

        dtrain = xgb.DMatrix(data=X, label=y)

        res = xgb.cv(params=params,
                     dtrain=dtrain,
                     num_boost_round=1000,
                     nfold=8,
                     stratified=False,
                     folds=None,
                     metrics=eval_metric,
                     early_stopping_rounds=100,
                     shuffle=True
                     )

        best_nrounds = res.shape[0] - 1

        temp_model = xgb.train(params=params,
                               dtrain=dtrain,
                               num_boost_round=best_nrounds
                               )

        temp_predictions = temp_model.predict(dtrain)

        print('mae:', mean_absolute_error(y, temp_predictions))

        results.append(mean_absolute_error(y, temp_predictions))


    return np.transpose(results)
```

### pyswarms call

```
from pyswarms.single.general_optimizer import GeneralOptimizerPSO
from pyswarms.backend.topology.von_neumann import VonNeumann
from pyswarms.utils.search.random_search import RandomSearch

from Python_Scripts.xgboost_optimization_func import xgboost_hp_search
```

```
        options = {
            'c1': 0.5,
            'c2': 0.4,
            'w': 0.75,
            'p': 2,
            'r': 4
        }

        inf_like = 999999999  # using for inf since np.inf causes a OverflowError in np.uniform

        lb = [0, 0, 0, 0, 0, 0.0000000001, 0.0000000001]
        ub = [1, inf_like, inf_like, inf_like, inf_like, 1, 1]

        optimizer = GeneralOptimizerPSO(
            n_particles=40,
            dimensions=7,
            options=options,
            topology=VonNeumann(),
            bounds=(lb, ub)
        )

        kwargs = {'X': X, 'y': y, 'eval_metric': eval_metric}

        results = optimizer.optimize(objective_func=xgboost_hp_search,
                                     iters=1000,
                                     # n_processes=24,
                                     **kwargs)
```

### Traceback

```
Traceback (most recent call last):
  File "C:/Users/caleb/OneDrive/Documents/GitHub/Initial_Production_Prediction_Model/main.py", line 228, in <module>
    main()
  File "C:/Users/caleb/OneDrive/Documents/GitHub/Initial_Production_Prediction_Model/main.py", line 111, in main
    y_train=data_dict['y_train']
  File "C:\Users\caleb\OneDrive\Documents\GitHub\Initial_Production_Prediction_Model\Python_Scripts\modeling.py", line 73, in __init__
    y_train=y_train)
  File "C:\Users\caleb\OneDrive\Documents\GitHub\Initial_Production_Prediction_Model\Python_Scripts\modeling.py", line 144, in __init__
    self.model = self.fit(x_train, y_train)
  File "C:\Users\caleb\OneDrive\Documents\GitHub\Initial_Production_Prediction_Model\Python_Scripts\modeling.py", line 217, in fit
    **kwargs)
  File "C:\Users\caleb\Anaconda3\envs\Initial_Production_Prediction_Model\lib\site-packages\pyswarms\single\general_optimizer.py", line 229, in optimize
    self.swarm, **self.options
  File "C:\Users\caleb\Anaconda3\envs\Initial_Production_Prediction_Model\lib\site-packages\pyswarms\backend\topology\von_neumann.py", line 50, in compute_gbest
    return super(VonNeumann, self).compute_gbest(swarm, p, k)
  File "C:\Users\caleb\Anaconda3\envs\Initial_Production_Prediction_Model\lib\site-packages\pyswarms\backend\topology\ring.py", line 78, in compute_gbest
    idx_min = swarm.pbest_cost[self.neighbor_idx].argmin(axis=1)
IndexError: index 40 is out of bounds for axis 0 with size 40
```

**Comment by whzup** [comment]
Hello @cembry26! It seems like something is not correct with your cost function, what shape does its output have?

**Comment by dangmanhtruong1995** [comment]
Hi, I also had this error although my code is not the same as that of OP's. For my case, I set the 'k' parameter (which is the number of local neighbors) to be higher than that of the population size, then I got the error. Once I changed 'k' to be smaller than the population size, this error went away.
